# Board: Generic ESP32-S3 Board (Generic)
# Definition: definitions/boards/generic-esp32s3/manifest.yaml
substitutions:
  text_font: nunito_20
  button_on_color: "ep_orange"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  display_daytime_brightness: "85%"
  display_nighttime_brightness: "50%"
  display_night_hour: "23"
  display_night_minute: "0"
  display_backlight_timeout_always_enabled: "true"
  display_backlight_timeout_initial: "15"
  screen_width: "480"
  screen_height: "480"

esphome:
  name: kitchen-controller
  friendly_name: kitchen_controller
  on_boot:
    - priority: 400
      then:
        - script.execute: update_loading_page

api:
  encryption:
    key: "en3Va83w/XcxLphoMwWEUbTu1BYzByttu/C2KdwFp/I="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid1
  password: !secret wifi_password1
  ap:
    ssid: kitchen_control Fallback Hotspot
    password: "nhNVzpRYJOwP"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

psram:

logger:

script:
  - id: time_update
    then:
      - lambda: return;

packages:
  
  wifi: !include esphome-modular-lvgl-buttons/common/wifi.yaml

  ota_screen: !include esphome-modular-lvgl-buttons/common/ota.yaml

  theme: !include esphome-modular-lvgl-buttons/common/theme/index.yaml

  sensors: !include esphome-modular-lvgl-buttons/common/sensors_base.yaml

  backlight: !include esphome-modular-lvgl-buttons/common/backlight_time.yaml

  idle_return_home: !include esphome-modular-lvgl-buttons/common/idle_return_home.yaml

  # rotation: rotated counter-clockwise 90° from the hardware default (180 -> 90)
  hardware: !include
    file: esphome-modular-lvgl-buttons/hardware/guition-esp32-s3-4848s040.yaml
    vars:
      rotation: "90"

  loading_screen: !include esphome-modular-lvgl-buttons/pages/loading.yaml

  info_screen: !include esphome-modular-lvgl-buttons/pages/info.yaml

  kitchen_light: !include
    file: esphome-modular-lvgl-buttons/ui/light/remote.yaml
    vars:
      uid: kitchen_light
      entity_id: "light.keuken"
      row: 0
      column: 0
      text: "Kitchen Light"
      icon: $mdi_ceiling_light
      scene_1_entity_id: "scene.keuken_night"
      scene_1_text: "Night"
      scene_1_icon: $mdi_weather_night
      scene_2_entity_id: "scene.keuken_1_2"
      scene_2_text: "1 & 2"
      scene_2_icon: $mdi_lightbulb_group

  hal_light: !include
    file: esphome-modular-lvgl-buttons/ui/light/remote.yaml
    vars:
      uid: hal_light
      entity_id:  "light.hal1"
      row: 1
      column: 0
      text: "Hal light"
      icon: $mdi_ceiling_light

  shut_down_my_office: !include
    file: esphome-modular-lvgl-buttons/ui/light/remote.yaml
    vars:
      uid: shut_down_my_office
      entity_id: "script.shut_down_my_office"
      row: 0
      column: 1
      text: "Shut Down Office"
      icon: $mdi_remote_desktop

  boiler_switch: !include
    file: esphome-modular-lvgl-buttons/ui/switch/remote.yaml
    vars:
      uid: boiler
      entity_id: "switch.switch_boiler"
      row: 2
      column: 1
      text: "Boiler"
      icon: $mdi_power_plug

  kitchen_blinds: !include
    file: esphome-modular-lvgl-buttons/ui/cover/cover_tilt_button.yaml
    vars:
      uid: kitchen_blinds
      row: 2
      column: 0
      text: "Blinds"
      icon: $mdi_blinds
      entity_id: "cover.blind_tilt_e1b4"
      hide_slider: "false"

  # KITCHEN RADIO

  kitchen_radio: !include
    file: esphome-modular-lvgl-buttons/ui/media_button/remote.yaml
    vars:
      uid: kitchen_radio
      row: 1
      column: 1
      text: "Radio"
      icon: $mdi_radio
      scene_entity_id: "scene.listen_stubru_kitchen"
      scene_text: "StuBru"
      scene_icon: $mdi_radio
      media_player_entity_id: "media_player.denon_avr_x3100w_2"
      zone2_entity_id: "media_player.denon_avr_x3100w_2"
      zone2_text: "Off"
      zone2_icon: $mdi_speaker_off
      stop_entity_id: "media_player.living_room_speaker_2"
      scene_2_entity_id: "scene.listen_boom_room_kitchen"
      scene_2_text: "Boom Room"
      scene_2_icon: $mdi_podcast
      input_entity_id: "media_player.denon_avr_x3100w"
      input_source: "Lvngrm speak"

lvgl:
  pages:
    - id: main_page
      layout: 3x2
      styles: page_style

      <<: !include esphome-modular-lvgl-buttons/common/swipe_navigation.yaml

font:
  - file: "https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf"
    id: mdi_icons_40
    size: 40
    bpp: 8

    glyphs:
      # Required by light detail page
      - $mdi_brightness_6
      - $mdi_chevron_up
      - $mdi_circle_opacity
      - $mdi_eyedropper
      - $mdi_lightbulb
      - $mdi_weather_night
      - $mdi_lightbulb_group

      # Main dashboard icons
      - $mdi_ceiling_light
      - $mdi_blinds
      - $mdi_clock_time_eight
      - $mdi_cellphone_charging
      - $mdi_information_box
      - $mdi_remote_desktop
      - $mdi_power_plug
      - $mdi_led_strip
      - $mdi_play
      - $mdi_pause
      - $mdi_skip_next
      - $mdi_skip_previous
      - $mdi_shuffle
      - $mdi_repeat
      - $mdi_repeat_once
      - $mdi_volume_high
      - $mdi_volume_minus
      - $mdi_volume_plus
      - $mdi_music_note
      - $mdi_radio
      - $mdi_podcast
      - $mdi_speaker_off
      - $mdi_speaker
      - $mdi_chevron_left
        
  - file: "gfonts://Nunito"
    id: nunito_2026
    size: 20
